name: video_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  # play videos
  flutter_downloader: ^1.7.4
  marquee_widget: ^1.2.0
  sqflite: ^2.0.2+1
  video_player: ^2.4.2
  weather: ^2.0.1

dev_dependencies:
  downloads_path_provider_28: ^0.1.2
  firebase_core: ^1.17.1
  firebase_database: ^9.0.15
  flutter_bloc: ^8.0.1
  flutter_test:
    sdk: flutter
  geolocator: ^8.2.1
  integration_test:
    sdk: flutter
  marquee: ^2.2.1
  nepali_utils: ^3.0.3
  path_provider: ^2.0.11
  permission_handler: ^9.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/video.mp4
    - assets/video1.mp4
    - assets/ntc.webp
