name: video_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  # pick video from file system
  file_picker: ^4.6.0
  flutter:
    sdk: flutter

  # play videos
  flutter_downloader: ^1.7.4
  video_player: ^2.4.2
  weather: ^2.0.1

dev_dependencies:
  flutter_bloc: ^8.0.1
  flutter_test:
    sdk: flutter
  geolocator: ^8.2.1
  integration_test:
    sdk: flutter
  marquee: ^2.2.1
  nepali_utils: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/video.mp4
    - assets/video1.mp4
    - assets/ntc.webp
